Translator.Locales = { dateorder: {} }
Translator.Locales.dateorder["af-za"] = Translator.Locales.dateorder["af"] = Translator.Locales.dateorder["afrikaans"] = "ymd"
Translator.Locales.dateorder["ar"] = Translator.Locales.dateorder["العربية"] = Translator.Locales.dateorder["arabic"] = "dmy"
Translator.Locales.dateorder["bg-bg"] = Translator.Locales.dateorder["bg"] = Translator.Locales.dateorder["Български"] = Translator.Locales.dateorder["bulgarian"] = "dmy"
Translator.Locales.dateorder["ca-ad"] = Translator.Locales.dateorder["ca"] = Translator.Locales.dateorder["català"] = Translator.Locales.dateorder["catalan"] = "dmy"
Translator.Locales.dateorder["cs-cz"] = Translator.Locales.dateorder["cs"] = Translator.Locales.dateorder["Čeština"] = Translator.Locales.dateorder["czech"] = "dmy"
Translator.Locales.dateorder["cy-gb"] = Translator.Locales.dateorder["cy"] = Translator.Locales.dateorder["cymraeg"] = Translator.Locales.dateorder["welsh"] = "dmy"
Translator.Locales.dateorder["da-dk"] = Translator.Locales.dateorder["da"] = Translator.Locales.dateorder["dansk"] = Translator.Locales.dateorder["danish"] = "dmy"
Translator.Locales.dateorder["de-at"] = Translator.Locales.dateorder["deutsch"] = Translator.Locales.dateorder["german"] = "dmy"
Translator.Locales.dateorder["de-ch"] = Translator.Locales.dateorder["deutsch"] = Translator.Locales.dateorder["german"] = "dmy"
Translator.Locales.dateorder["de-de"] = Translator.Locales.dateorder["de"] = Translator.Locales.dateorder["deutsch"] = Translator.Locales.dateorder["german"] = "dmy"
Translator.Locales.dateorder["el-gr"] = Translator.Locales.dateorder["el"] = Translator.Locales.dateorder["Ελληνικά"] = Translator.Locales.dateorder["greek"] = "dmy"
Translator.Locales.dateorder["en-gb"] = Translator.Locales.dateorder["en"] = Translator.Locales.dateorder["english"] = "dmy"
Translator.Locales.dateorder["en-us"] = Translator.Locales.dateorder["american"] = "mdy"
Translator.Locales.dateorder["es-cl"] = Translator.Locales.dateorder["español"] = Translator.Locales.dateorder["spanish"] = "dmy"
Translator.Locales.dateorder["es-es"] = Translator.Locales.dateorder["es"] = Translator.Locales.dateorder["español"] = Translator.Locales.dateorder["spanish"] = "dmy"
Translator.Locales.dateorder["es-mx"] = Translator.Locales.dateorder["español"] = Translator.Locales.dateorder["spanish"] = "dmy"
Translator.Locales.dateorder["et-ee"] = Translator.Locales.dateorder["et"] = Translator.Locales.dateorder["eesti"] = Translator.Locales.dateorder["estonian"] = "dmy"
Translator.Locales.dateorder["eu"] = Translator.Locales.dateorder["euskara"] = Translator.Locales.dateorder["basque"] = "ymd"
Translator.Locales.dateorder["fa-ir"] = Translator.Locales.dateorder["fa"] = Translator.Locales.dateorder["فارسی"] = Translator.Locales.dateorder["persian"] = "mdy"
Translator.Locales.dateorder["fi-fi"] = Translator.Locales.dateorder["fi"] = Translator.Locales.dateorder["suomi"] = Translator.Locales.dateorder["finnish"] = "dmy"
Translator.Locales.dateorder["fr-ca"] = Translator.Locales.dateorder["français"] = Translator.Locales.dateorder["french"] = "dmy"
Translator.Locales.dateorder["fr-fr"] = Translator.Locales.dateorder["fr"] = Translator.Locales.dateorder["français"] = Translator.Locales.dateorder["french"] = "dmy"
Translator.Locales.dateorder["he-il"] = Translator.Locales.dateorder["he"] = Translator.Locales.dateorder["עברית"] = Translator.Locales.dateorder["hebrew"] = "dmy"
Translator.Locales.dateorder["hr-hr"] = Translator.Locales.dateorder["hr"] = Translator.Locales.dateorder["hrvatski"] = Translator.Locales.dateorder["croatian"] = "ymd"
Translator.Locales.dateorder["hu-hu"] = Translator.Locales.dateorder["hu"] = Translator.Locales.dateorder["magyar"] = Translator.Locales.dateorder["hungarian"] = "ymd"
Translator.Locales.dateorder["id-id"] = Translator.Locales.dateorder["id"] = Translator.Locales.dateorder["bahasa indonesia"] = Translator.Locales.dateorder["indonesian"] = "dmy"
Translator.Locales.dateorder["is-is"] = Translator.Locales.dateorder["is"] = Translator.Locales.dateorder["Íslenska"] = Translator.Locales.dateorder["icelandic"] = "dmy"
Translator.Locales.dateorder["it-it"] = Translator.Locales.dateorder["it"] = Translator.Locales.dateorder["italiano"] = Translator.Locales.dateorder["italian"] = "dmy"
Translator.Locales.dateorder["ja-jp"] = Translator.Locales.dateorder["ja"] = Translator.Locales.dateorder["日本語"] = Translator.Locales.dateorder["japanese"] = "ymd"
Translator.Locales.dateorder["km-kh"] = Translator.Locales.dateorder["km"] = Translator.Locales.dateorder["ភាសាខ្មែរ"] = Translator.Locales.dateorder["khmer"] = "dmy"
Translator.Locales.dateorder["ko-kr"] = Translator.Locales.dateorder["ko"] = Translator.Locales.dateorder["한국어"] = Translator.Locales.dateorder["korean"] = "ymd"
Translator.Locales.dateorder["lt-lt"] = Translator.Locales.dateorder["lt"] = Translator.Locales.dateorder["lietuvių"] = Translator.Locales.dateorder["lithuanian"] = "ymd"
Translator.Locales.dateorder["lv-lv"] = Translator.Locales.dateorder["lv"] = Translator.Locales.dateorder["latviešu"] = Translator.Locales.dateorder["latvian"] = "dmy"
Translator.Locales.dateorder["mn-mn"] = Translator.Locales.dateorder["mn"] = Translator.Locales.dateorder["Монгол"] = Translator.Locales.dateorder["mongolian"] = "ymd"
Translator.Locales.dateorder["nb-no"] = Translator.Locales.dateorder["nb"] = Translator.Locales.dateorder["norsk bokmål"] = Translator.Locales.dateorder["norwegian"] = "ymd"
Translator.Locales.dateorder["nl-nl"] = Translator.Locales.dateorder["nl"] = Translator.Locales.dateorder["nederlands"] = Translator.Locales.dateorder["dutch"] = "dmy"
Translator.Locales.dateorder["nn-no"] = Translator.Locales.dateorder["nn"] = Translator.Locales.dateorder["norsk nynorsk"] = Translator.Locales.dateorder["norwegian"] = "ymd"
Translator.Locales.dateorder["pl-pl"] = Translator.Locales.dateorder["pl"] = Translator.Locales.dateorder["polski"] = Translator.Locales.dateorder["polish"] = "dmy"
Translator.Locales.dateorder["pt-br"] = Translator.Locales.dateorder["português"] = Translator.Locales.dateorder["portuguese"] = "dmy"
Translator.Locales.dateorder["pt-pt"] = Translator.Locales.dateorder["pt"] = Translator.Locales.dateorder["português"] = Translator.Locales.dateorder["portuguese"] = "dmy"
Translator.Locales.dateorder["ro-ro"] = Translator.Locales.dateorder["ro"] = Translator.Locales.dateorder["română"] = Translator.Locales.dateorder["romanian"] = "dmy"
Translator.Locales.dateorder["ru-ru"] = Translator.Locales.dateorder["ru"] = Translator.Locales.dateorder["Русский"] = Translator.Locales.dateorder["russian"] = "dmy"
Translator.Locales.dateorder["sk-sk"] = Translator.Locales.dateorder["sk"] = Translator.Locales.dateorder["slovenčina"] = Translator.Locales.dateorder["slovak"] = "dmy"
Translator.Locales.dateorder["sl-si"] = Translator.Locales.dateorder["sl"] = Translator.Locales.dateorder["slovenščina"] = Translator.Locales.dateorder["slovenian"] = "dmy"
Translator.Locales.dateorder["sr-rs"] = Translator.Locales.dateorder["sr"] = Translator.Locales.dateorder["Српски / srpski"] = Translator.Locales.dateorder["serbian"] = "ymd"
Translator.Locales.dateorder["sv-se"] = Translator.Locales.dateorder["sv"] = Translator.Locales.dateorder["svenska"] = Translator.Locales.dateorder["swedish"] = "ymd"
Translator.Locales.dateorder["th-th"] = Translator.Locales.dateorder["th"] = Translator.Locales.dateorder["ไทย"] = Translator.Locales.dateorder["thai"] = "dmy"
Translator.Locales.dateorder["tr-tr"] = Translator.Locales.dateorder["tr"] = Translator.Locales.dateorder["türkçe"] = Translator.Locales.dateorder["turkish"] = "dmy"
Translator.Locales.dateorder["uk-ua"] = Translator.Locales.dateorder["uk"] = Translator.Locales.dateorder["Українська"] = Translator.Locales.dateorder["ukrainian"] = "dmy"
Translator.Locales.dateorder["vi-vn"] = Translator.Locales.dateorder["vi"] = Translator.Locales.dateorder["tiếng việt"] = Translator.Locales.dateorder["vietnamese"] = "dmy"
Translator.Locales.dateorder["zh-cn"] = Translator.Locales.dateorder["zh"] = Translator.Locales.dateorder["中文"] = Translator.Locales.dateorder["chinese"] = "ymd"
Translator.Locales.dateorder["zh-tw"] = Translator.Locales.dateorder["中文"] = Translator.Locales.dateorder["chinese"] = "ymd"
