#!/usr/bin/env python3

from urllib.request import urlretrieve
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile

import pathlib
for d in pathlib.Path(__file__).resolve().parents:
  if os.path.exists(os.path.join(d, 'behave.ini')):
    ROOT = d
    break
os.chdir(ROOT)

# because behave doesn't think it's useful to be able to load local stuff... oy...
sys.path.insert(0, os.path.abspath('test/features/steps'))

parser = argparse.ArgumentParser()
parser.add_argument('--no-stop', action='store_true')
parser.add_argument('--nightly', action='store_true')
parser.add_argument('--jurism', action='store_true')
parser.add_argument('--beta', action='store_true')

args, unknownargs = parser.parse_known_args()
sys.argv = sys.argv[:1] + unknownargs

## exclude @nightly by default
nightly = any([
  args.nightly,                                               # requested explicitly from the command line
  '#nightly' in os.environ.get('TRAVIS_COMMIT_MESSAGE', ''),  # requested explicitly through the commit message
  os.environ.get('TRAVIS_TAG', '') != '',                     # running a release build
  os.environ.get('TRAVIS_EVENT_TYPE') == 'cron',          # running the nightly build
])
if not nightly: sys.argv.extend(['--tags', '~@nightly'])

if 'CI' in os.environ: # set up for CI
  sys.argv.extend(['--define', f'client={os.environ["CLIENT"]}'])
  oddjob = (os.environ['JOB'] == '2')

  if nightly and os.environ.get('TRAVIS_TAG', '') == '': # don't run beta on tagged builds
    args.beta = oddjob

  else: # run regular tests
    sys.argv.extend(['--tags', f'{"~" if oddjob else ""}@test-cluster-1'])

else: # local client run
  ## stop on first error by default
  if not args.no_stop: sys.argv.append('--stop')

  if args.jurism: sys.argv.extend(['--define', f'client=jurism'])

  # build before test unless on CI
  process = subprocess.Popen(['npm', 'run', 'build'], stdout=subprocess.PIPE)
  while True:
    line = process.stdout.readline()
    print(line.decode('utf-8'), end='')
    if process.poll() is not None: break
  returncode = process.poll()
  if returncode != 0:
    print(f'Build exited with exit code {returncode}')
    sys.exit(returncode)

if args.beta: sys.argv.extend(['--define', f'beta=true'])

print(' '.join(sys.argv))

#https://stackoverflow.com/questions/28829350/run-python-behave-from-python-instead-of-command-line
from behave.__main__ import Configuration, run_behave
sys.exit(run_behave(Configuration(None)))
