#ruby=2.2.4
#ruby-gemset=zotero

source 'https://rubygems.org'

gem 'trollop' # for AWS creds parser
gem 'addressable'
gem 'aws-sdk', '~> 2'
gem 'bibtex-ruby'
gem 'cucumber'
gem 'facets'
gem 'faraday-http-cache'
gem 'front_matter_parser'
gem 'ghi'
gem 'git'
gem 'headless'
gem 'jwt'
gem 'mechanize'
gem 'moving_average'
gem 'net-sftp'
gem 'nokogiri'
gem 'octokit'
gem 'os'
gem 'rake'
gem 'rake-xpi'
gem 'rchardet'
gem 'recursive-open-struct'
gem 'rest-client'
gem 'rspec'
gem 'rubyzip', '>= 1.0.0' # will load new rubyzip version
gem 'selenium-webdriver' , '2.53.4'
gem 'sqlite3'
gem 'travis'
gem 'travis_parallel_sentinel'
gem 'typhoeus'
gem 'washbullet'
gem 'zip-zip' # will load compatibility for old rubyzip API.
gem 'shell-spinner'
gem 'regexp_parser'
gem 'progressbar'
gem 'github_changelog_generator'
