source 'https://rubygems.org'

gem 'ffi', '~> 1.9.24'
gem 'travis'
gem 'cucumber'
gem 'headless'
gem 'os'
gem 'rspec'
gem 'selenium-webdriver' , '2.53.4'
gem 'neatjson'
gem 'inifile'
gem 'httparty'
gem 'reverse_markdown'
gem 'deepsort'
gem "sqlite3"
gem 'aws-sdk'
gem 'dedent'
gem 'liquid'
gem 'facets'
gem 'dotenv'
