#ruby=2.2
#ruby-gemset=zotero

source 'https://rubygems.org'

gem 'os'
#gem 'trollop'
gem 'rake'
gem 'nokogiri'
gem 'bibtex-ruby'
#gem 'rubytree'
#gem 'chronic'
#gem 'activesupport'
#gem 'i18n'
#gem 'json-minify'
gem 'headless'
gem 'selenium-webdriver' # , '2.45.0.dev3'
gem 'cucumber'
gem 'rspec'
gem 'addressable'
gem 'rubyzip', '>= 1.0.0' # will load new rubyzip version
gem 'zip-zip' # will load compatibility for old rubyzip API.
gem 'typhoeus'
gem 'zotplus-rakehelper'
gem 'github_api'
gem 'travis'
gem 'washbullet'
gem 'travis_parallel_sentinel'
gem 'rchardet'
gem 'ghi'
gem 'multipart-post'
gem 'mechanize'
gem 'facets'
gem 'aws-sdk', '~> 2'
gem 'jwt'
gem 'multipart-post'
