name: Bug Report/Feature request
description: File a bug report or a feature request
title: "[Bug/Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Use this form if you think you want a change to BBT.

        Alongside a description of your problem/question/feature suggestion, please also include a debug log ID.

        You can generate a debug log ID by:
        1. reproducing the problem
        2. selecting the problematic reference(s)
        3. right-clicking them
        4. choose `BBT debug log` from the popup menu.

        If you are sure your question does not relate to items in your library at all, just select any one item in your library.
  - type: input
    id: debug-log
    attributes:
      label: Debug log ID
      placeholder: ex. ABCD1234-ref-euc
    validations:
      required: true
  - type: textarea
    id: request
    attributes:
      label: What happened?
      description: What did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
