#!/usr/bin/env python3

import sys, os
import json
from contextlib import suppress
from munch import Munch

print(sys.argv[1])
github = json.loads(sys.argv[1], object_hook=Munch.fromDict)
with open('package.json') as f:
  package = json.load(f, object_hook=Munch.fromDict)

flags = set()

with suppress(KeyError,AttributeError): # release build
  if github.event.head_commit.message == package.version and github.ref == f'refs/tags/{package.version}':
    print('release build')
    flags.add('slow')
    flags.add('beta')

with suppress(KeyError,AttributeError):
  if github.event_name == 'schedule': # nightlies
    print('nightly')
    flags.add('slow')
    flags.add('beta')

with suppress(KeyError,AttributeError):
  if github.ref_name == 'master': # master
    print('master')
    flags.add('slow')
    flags.add('beta')

#with suppress(KeyError,AttributeError):
if True:
  if os.path.isfile('beta.txt'):
    with open('beta.txt') as f:
      for branch in f.readlines():
        if branch.strip() == github.ref_name:
          print('beta for', github.ref_name)
          flags.add('beta')

print('flags =', flags)

if len(flags) > 0:
  with open(os.environ['GITHUB_ENV'], 'a') as env:
    for flag in flags:
      print(f'{flag}=--{flag}', file=env)
