#!/usr/bin/env python

import editor, json, sys

with open(sys.argv[1]) as f:
  lib = json.load(f)

if not 'config' in lib: sys.exit(0)
if not 'preferences' in lib['config']: sys.exit(0)
if not 'postscript' in lib['config']['preferences']: sys.exit(0)

lib['config']['preferences']['postscript'] = editor.edit(contents=lib['config']['preferences']['postscript']).decode('utf-8')

with open(sys.argv[1], 'w') as f:
  json.dump(lib, f, indent='  ')
