#!/usr/bin/env python3

import tarfile
import os
import sys
import shutil
from urllib.request import urlretrieve

if not 'CI' in os.environ: sys.exit(0)
if os.environ.get('CLIENT') != 'zotero': sys.exit(0)
if os.environ.get('INSTALL_BETA') != 'true': sys.exit(0)

print('Installing Zotero beta')
urlretrieve('https://www.zotero.org/download/standalone/dl?platform=linux-x86_64&channel=beta', 'client.tar.bz2')

target = '/usr/lib/zotero'
if os.path.exists(target): shutil.rmtree(target)
os.mkdir(target)

tar = tarfile.open('client.tar.bz2')
for member in tar.getmembers():
  if not member.isreg(): continue
  member.name = re.sub(r'^.+?\/', '', member.name) # strip leading directory

  if member.name in ['zotero.desktop', 'jurism.desktop', 'active-update.xml', 'precomplete', 'removed-files', 'updates', 'updates.xml']:
    continue

  tar.extract(member, target)
tar.close()
