#!/usr/bin/env python3

import plistlib
import os
import sys

client = sys.argv[1] if len(sys.argv) == 2 else 'zotero'
assert client in ['zotero', 'jurism'], client

root = f'/Applications/{client.title()}.app/Contents'
launcher = root + f'/MacOS/{client}-p-datadir'
zotero = root + f'/MacOS/{client}'
info = root + '/Info.plist'

with open(launcher, 'w') as f:
  f.write('#!/bin/bash\n')
  f.write('set -x\n')
  f.write(f'{zotero} -P -datadir profile\n')

os.chmod(launcher, os.stat(zotero).st_mode)

print(info)
with open(info, 'rb') as f:
  plist = plistlib.load(f)
plist['CFBundleExecutable'] = os.path.basename(launcher)
with open(info, 'wb') as f:
  plistlib.dump(plist, f)

os.system('find /System/Library/Frameworks -type f -name "lsregister" -exec {} -kill -seed -r \;')
