export interface ISerializedItem {
  DOI: any
  ISBN: any
  ISSN: any
  abstractNote: any
  accessDate: any
  applicationNumber: any
  archive: any
  archiveLocation: any
  artworkSize: any
  assignee: any
  callNumber: any
  code: any
  codeNumber: any
  committee: any
  conferenceName: any
  country: any
  court: any
  date: any
  edition: any
  extra: any
  filingDate: any
  history: any
  issue: any
  issuingAuthority: any
  journalAbbreviation: any
  language: any
  legalStatus: any
  legislativeBody: any
  libraryCatalog: any
  medium: any
  meetingName: any
  numPages: any
  number: any
  numberOfVolumes: any
  pages: any
  place: any
  priorityNumbers: any
  programmingLanguage: any
  publicationTitle: any
  publisher: any
  references: any
  reporter: any
  rights: any
  runningTime: any
  scale: any
  section: any
  series: any
  seriesNumber: any
  seriesText: any
  seriesTitle: any
  session: any
  shortTitle: any
  system: any
  title: any
  type: any
  url: any
  versionNumber: any
  volume: any
  volumeTitle: any
  multi: any
  __type__: any
  attachments: any
  tags: any
}
