export interface ISerializedItem {
  DOI: any
  ISBN: any
  ISSN: any
  abstractNote: any
  accessDate: any
  applicationNumber: any
  archive: any
  archiveLocation: any
  artworkSize: any
  assignee: any
  callNumber: any
  code: any
  codeNumber: any
  committee: any
  conferenceName: any
  country: any
  court: any
  date: any
  edition: any
  extra: any
  filingDate: any
  history: any
  issue: any
  issuingAuthority: any
  journalAbbreviation: any
  language: any
  legalStatus: any
  legislativeBody: any
  libraryCatalog: any
  medium: any
  meetingName: any
  numPages: any
  number: any
  numberOfVolumes: any
  pages: any
  place: any
  priorityNumbers: any
  programmingLanguage: any
  publicationTitle: any
  publisher: any
  references: any
  reporter: any
  rights: any
  runningTime: any
  scale: any
  section: any
  series: any
  seriesNumber: any
  seriesText: any
  seriesTitle: any
  session: any
  shortTitle: any
  system: any
  title: any
  type: any
  url: any
  versionNumber: any
  volume: any

  itemType: string
  dateModified: string
  dateAdded: string
  notes: string[]
  tags: string[]
  collections: any[]
  creators: any[]
  attachments: any[]
  itemID: any
  multi: any

  citekey: string
  cslType: string
  volumeTitle: string
  __type__: string
  extraFields: { bibtex: { [key: string]: { name: string, type: string, value: any } }, csl: { [key: string]: { name: string, type: string, value: any } }, kv: { [key: string]: { name: string, type: string, value: string, raw?: boolean } } }
  arXiv: { eprint: string, source?: string, id: string, primaryClass?: string }
}
