gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme", group: :jekyll_plugins
gem 'jekyll-optional-front-matter', group: :jekyll_plugins
gem "jekyll-readme-index", group: :jekyll_plugins
gem 'jekyll-default-layout', group: :jekyll_plugins
gem 'jekyll-titles-from-headings', group: :jekyll_plugins
